const FILESPATH = './files';
const PERFORMANCEMINBOARDSIZE = 1000;
const PERFORMANCEMAXBOARDSIZE = 2*PERFORMANCEMINBOARDSIZE;
const PERFORMANCENUMBEROFTESTS = 10;
const BOARD0 = ``;
const BOARD1 = ` `;
const BOARD2 = ` #\n# `;
const BOARD3 = ` # \n# #\n # `;
const BOARD20 = Array(10).fill(" # # # # # # # # # #\n# # # # # # # # # # ").join('\n');
const TESTINGBOARDS = {0:BOARD0,1:BOARD1,2:BOARD2,3:BOARD3,20:BOARD20};

module.exports = {FILESPATH,PERFORMANCEMINBOARDSIZE,PERFORMANCEMAXBOARDSIZE,PERFORMANCENUMBEROFTESTS,TESTINGBOARDS}
